@startuml
start

:Load data_collection from `get_pull_requests.py`;
:For every main issue, collect it's parents (better context)
and use AI to write a summary for a developer;
:Compute embeddings for every main issue
(original text + ai summary) for RAG;
:Select the top (default 5) issues that might match (RAG);
:Ask AI to select matching jira issues out of those;
stop
@enduml