@startuml
start
:Get all PRs from the org/author given;
:Get all jira issues from the given "top level filter";
:Get all children of those main issues;
:Search the PR title and description for jira references;
:For every issue fetch all it's parents issues;
:Save all data (PRs, main issues, related issues) to disk;
stop
@enduml